import argparse

parser = argparse.ArgumentParser(description='entity linker')
parser.add_argument("--output_path",type=str,default="output")
parser.add_argument("--lang", type=list, default=['ja','de','es','ar','sr','tr','fa','ta','en','fr','it'])
parser.add_argument("--training_path", type=str, default='./data/wikipedia/gold_entities')
parser.add_argument('--tmp_path',type=str,default='./data/tmp')
parser.add_argument('--entity_count_path',type=str,default='./data/wikipedia/entity_freq.csv')
parser.add_argument('--entity_description_path',type=str,default='./data/wikipedia/entity_descriptions.csv')
parser.add_argument('--entity_def_path',type=str,default='./data/wikipedia/entity_defs.csv')
parser.add_argument('--prior_for_des_path',type=str,default='./data/wikipedia/prior_prob.pkl')
parser.add_argument('--entity2id',type=str,default='./data/tmp/entity2id.pkl')
parser.add_argument('--random_description',default=True,type=bool)
parser.add_argument('--entity2description',type=str,default='./data/tmp/entity2description.pkl')
parser.add_argument("--processed_data_path", type=str, default='./data/wikipedia/gold_entities_processed.jsonl')
parser.add_argument("--candidates_data_path", type=str, default='./data/wikipedia/candidates.pkl')
parser.add_argument("--epochs", type=int, default=10)
parser.add_argument('--bert_model',default="bert-base-multilingual-cased",type=str)
parser.add_argument('--lowercase',default=False,type=bool)
parser.add_argument("--train_batch_size", type=int, default=64)
parser.add_argument("--eval_batch_size", type=int, default=64)
parser.add_argument("--gradient_accumulation_steps", type=int, default=1)
parser.add_argument("--max_context_length", type=int, default=64,help='total context length')
parser.add_argument("--max_cand_length", type=int, default=64)
parser.add_argument("--context_key", default="context", type=str)
parser.add_argument('--shuffle',type=bool,default=True)
parser.add_argument("--learning_rate",default=3e-5,type=float,help="The initial learning rate for Adam.")
parser.add_argument('--fp16',type=bool,default=False)
parser.add_argument('--weight_decay',type=float,default=0.01)
parser.add_argument('--out_dim',type=int,default=100)
parser.add_argument('--warmup_proportion',type=float,default=0.01)
parser.add_argument('--print_interval',type=int,default=1)
parser.add_argument('--eval_interval',type=int,default=1)
parser.add_argument("--max_grad_norm", default=1.0, type=float)
parser.add_argument('--seed', type=int, default=42)
parser.add_argument('--data_parallel',type=bool,default=False)

parser.add_argument('--add_linear',type=bool,default=True)
parser.add_argument("--pull_from_layer", type=int, default=-1, help="Layers to pull from BERT")
parser.add_argument("--index_buffer", type=int, default=50000)
parser.add_argument("--top_k", type=int, default=10)
parser.add_argument('--type_optimization',type=str, default='top4_layers')
parser.add_argument('--in_batch_neg',type=bool,default=False)
parser.add_argument('--debug',default=True,type=bool)
parser.add_argument('--epoch_of_in_batch_neg',type=int, default=5)
parser.add_argument('--eval_list',type=list,default=[1,100])